name: MVF
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  go_router: ^12.1.1
  flutter_hooks: ^0.20.2
  hooks_riverpod: ^2.4.2
  image_picker: ^1.0.4
  file_picker: ^6.0.0
  chewie: ^1.7.4
  chewie_audio: ^1.5.0
  video_player: ^2.8.1
  ffmpeg_kit_flutter: ^6.0.3
  translator: ^0.1.7
  dart_openai:
  flutter_tts: ^3.8.5
  record: ^5.0.4
  flutter_launcher_icons: ^0.13.1
  buttons_tabbar: ^1.3.8
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icons/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/icons/app_icon.png

  # To add custom fonts to your application, add a fonts section here,
  fonts:
    - family: Quicksand
      fonts:
        - asset: asset/fonts/Quicksand-Bold.ttf
        - asset: asset/fonts/Quicksand-Light.ttf
        - asset: asset/fonts/Quicksand-Medium.ttf
        - asset: asset/fonts/Quicksand-Regular.ttf
        - asset: asset/fonts/Quicksand-SemiBold.ttf
        - asset: asset/fonts/Quicksand-VariableFont_wght.ttf



